name: cmake
run-name: cmake

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_TYPE=Release -Dcharwidth_project=ON -Dcharwidth_project_lib=OFF
          cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build -C Release -V
