name: cmake
run-name: cmake

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  #  job_1:
  #    strategy:
  #      matrix:
  #        os: [ubuntu-latest, windows-latest, macos-latest]
  #    runs-on: ${{ matrix.os }}
  #    name: ${{ matrix.os }} test
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v4
  #      - name: Build
  #        run: |
  #          mkdir build
  #          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_TYPE=Release -Dcharwidth_project=ON -Dcharwidth_project_lib=OFF
  #          cmake --build build --config Release
  #      - name: Test
  #        run: ctest --test-dir build -C Release -V

  job_2:
    runs-on: windows-latest
    name: windows-latest MinGW test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            make
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_TYPE=Release -Dcharwidth_project=ON -Dcharwidth_project_lib=OFF
          cmake --build build --config Release
      - name: Test
        shell: msys2 {0}
        run: ctest --test-dir build -C Release -V


