name: test.windows.msvc
run-name: test.windows.msvc

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest
    name: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -Dcharwidth_project=ON -Dcharwidth_project_lib=OFF
          cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build -C Release -V
