name: test.ubuntu.gcc
run-name: test.ubuntu.gcc

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -Dcharwidth_project=ON -Dcharwidth_project_lib=OFF
          cmake --build build

      - name: Run test
        run: ctest --test-dir build -V
